[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "18"
  
[build]
  publish = "docs/.vitepress/dist"
  command = "npx pnpm --store=node_modules/.pnpm-store --no-frozen-lockfile && npm run docs:build"